### ISSUE TITLE
Add credit to link to this template

### ISSUE THREAD

**Issue by ShashankBice** [uwhackweek/splashpage-template#1]
Hi team,
Thanks for sharing this great resource, we used it to make a website for the upcoming Northwest Glaciologists meeting [here](https://nwgmeetings.github.io/nwg23/). The source repository lives [here](https://github.com/nwgmeetings/nwg23). I would like some guidance on how we can acknowledge this beautiful template provided by the hackweek team at page footer. I am not a HTML expert, I googled and somehow edited the template to get the website running how we wanted it to be, so I would appreciate guidance on how acknowledgement to the spashplage template made by the eScience Hackweek team can be included after the designed by message :)
![Screenshot 2023-09-18 at 3 06 21 PM](https://github.com/uwhackweek/splashpage-template/assets/29011666/40c09faf-9658-4b67-92af-d80f3402f844)

cc (@jomey, @scottyhq, @lsetiawan)

Cheers,
Shashank

**Comment by jomey** [comment]
You can add a snippet like this:
```HTML
        <small class="copyright">
           This template was forked from the University of Washington eScience Institute
            <a href="https://github.com/uwhackweek" target="_blank">
               Hackweek program
            </a>.
        </small>
```
After this line:
https://github.com/uwhackweek/splashpage-template/blob/bed820e4018eb1573076608c0313e943b15ed2a2/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/index.html#L566

The `href` in the example points to the general GitHub page and you might want to adjust that. And any of the text of course 😄

**Comment by ShashankBice** [comment]
Thanks Joe for the prompt response. I added this to the NWG website. Shall I also add this to the current source template (this repository) so that it is carried forward in future forks?

**Comment by jomey** [comment]
Sounds good. PR away!

**Comment by ShashankBice** [comment]
Closing this as the PR has been merged :blush:
