### ISSUE TITLE
List formats in the schedule tab

### ISSUE THREAD

**Issue by ShashankBice** [uwhackweek/splashpage-template#2]
Hi folks,
I would like to create a list of talks in each session of the schedule (see example screenshot below). Maybe it is possible through the extended description class as in the [geosmarthackweek webpage](https://github.com/geo-smart/2023-hackweek-website/blob/6adc2ee8e6a478a889e0bca0841d0f82ef4bc859/cookiecutter.yaml#L39). I tried copying in the syntax from the index.html file of geosmart and copy to NWG repo, and then tried to add the extended_description tab in the schedule.yaml, but was not able to get it to work :( 
Would really appreciate some guidance on this :) We aim to update the schedule in the coming 2 weeks, so we have some time :)

cc (@jomey, @scottyhq, @lsetiawan)
Thanks again,
Shashank
![Screenshot 2023-09-18 at 3 12 37 PM](https://github.com/uwhackweek/splashpage-template/assets/29011666/81ddfbf6-89e1-49fb-b93e-f22e175b9002)

**Comment by jomey** [comment]
You could try using the `resources` option from the schedule. Here an example from the ICESat-2 Hackweek.
https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/4f8458040f6dc007e4e709ffea3e880d32cae9c0/book/schedule.yaml#L16

Then change this line in the template:
https://github.com/uwhackweek/splashpage-template/blob/bed820e4018eb1573076608c0313e943b15ed2a2/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/index.html#L323

to ‘Talks’

**Comment by ShashankBice** [comment]
Thanks Joe! This works, I had to get rid of the url link rendering in the html, but we are all set on this as well!!

Thanks again so much 😊 
Shashank
